package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the buildType with id = 'Danbooru'
accordingly, and delete the patch script.
*/
changeBuildType(RelativeId("Danbooru")) {
    check(artifactRules == "./danbooru/build/libs/* => danbooru") {
        "Unexpected option value: artifactRules = $artifactRules"
    }
    artifactRules = """
        ./danbooru/build/libs/* => danbooru
        ./danbooru/build/reports/jacoco/test/html/* => danbooru-jacoco-report
    """.trimIndent()
}
