package post

import Time

// should be checked later again
// todo was not completed
data class DanbooruPost(
    override val raw: Map<String, String>,
    override val postId: Int,
    override val creationTime: Time,
    val uploaderId: Int,
    override val score: Int,
    override val md5: String,
    val lastCommentBumpedTime: Time,
    override val fullImage: FullImage,
    override val tags: Tags,
    val isNoteLocked: Boolean,
    val favoriteCount: Int,
    val lastNotedTime: Time,
    val isRatingLocked: Boolean,
    val parentId: Int,
    val approverId: Int,
    val tagCountGeneral: Int,
    val tagCountArtist: Int,
    val tagCountCharacter: Int,
    val tagCountCopyright: Int,
    val fileSize: Int,
    val isStatusLocked: Boolean,
    val poolString: String,
    val upScore: Int,
    val downScore: Int,
    val isPending: Boolean,
    val isFlagged: Boolean,
    val isDeleted: Boolean,
    val tagCount: Int,
    val updationTime: Time,
    val isBanned: Boolean,
    val pixivId: Int,
    val lastCommentedTime: Time,
    val hasActiveChildren: Boolean,
    val bitFlags: Int,
    val tagCountMeta: Int,
    val hasLarge: Boolean,
    val hasVisibleChildren: Boolean,
    val isFavorite: Boolean,
    val tagStringGeneral: String,
    val tagStringCharacter: String,
    val tagStringCopyright: String,
    val tagStringArtist: String,
    val tagStringMeta: String,
    val hasChildren: Boolean,
    override val rating: Rating,
    override val source: String,
    override val hasComments: Boolean,
    override val previewImage: PreviewImage,
    override val sampleImage: SampleImage
) : Post

